Cargo.toml, src/objects/num.rs
This function was removed from the rust stdlib in https://github.com/rust-lang/rust/commit/eeb948.
Updated to refer to the 'num' crate instead.
=> Fix refs to std::num::cast -> num::traits::cast

python27-sys/Cargo.toml, python27-sys/build.rs, python27-sys/src/bytearrayobject.rs, python27-sys/src/ceval.rs, python27-sys/src/classobject.rs, python27-sys/src/complexobject.rs, python27-sys/src/floatobject.rs, python27-sys/src/intobject.rs, python27-sys/src/lib.rs, python27-sys/src/listobject.rs, python27-sys/src/longobject.rs, python27-sys/src/memoryobject.rs, python27-sys/src/methodobject.rs, python27-sys/src/modsupport.rs, python27-sys/src/object.rs, python27-sys/src/pyerrors.rs, python27-sys/src/pystate.rs, python27-sys/src/stringobject.rs, python27-sys/src/tupleobject.rs, python27-sys/src/unicodeobject.rs
* in build.rs, call the python interpreter located by pkgconfig
and use sysconfig to determine the flags it was built with.
* pass these flags to the build via --cfg
* refactor existing references to features to refer to these
instead
background - I'm trying to get this to build on os x, and apparently the homebrew python 2.7 is a utf-16 build (?!) so seemed logical to get this working (another pr coming soon for some blips in string conversion under utf-16).
this would need to be replicated across to python 3 also; would be keen to hear your thoughts on how best to share code between the two build.rs scripts for the two ffis.
=> dynamically determine python flags for cfg

.travis.yml, Cargo.toml, build.rs, python27-sys/Cargo.toml, python27-sys/build.rs, python27-sys/src/unicodeobject.rs, src/lib.rs, src/objects/string.rs
* fix ucs4 build broken by bb13ec
* add utf16 decoding to unicode.from_py_object for
narrow unicode builds
* change unicode narrow/wide cfg flag to be
Py_UNICODE_SIZE_4 not Py_UNICODE_WIDE, which doesn't
appear in sysconfig
* support framework builds on os x
* python27-sys exports compilation flags as cargo vars,
and rust-python resurrects them as cfg flags
* travis runs against local python27-sys
* rust-cpython depends on git python27-sys, because
the one on cargo is now incompatible with it (since bb13ec)
Okay, so things were a little complicated than I previous thought :/
1. The CI was actually running off crates.io's python27-sys, so I didn't realise I had a bunch of things wrong and had actually broken the build - sorry :/. I am still learning about the rust build system. In this …
=> fix issues in bb13ec, support utf16, python fom PATH

.travis.yml, Cargo.toml, build.rs, python27-sys/Cargo.toml, python27-sys/build.rs, python3-sys/Cargo.toml, python3-sys/build.rs, src/lib.rs
* Add python3-sys to rust-cpython as an optional feature, and
make python27-sys also optional, but still the default
* Parametrise python27-sys/build.rs so that it is python
version independent, and clone it into python3-sys/build.rs.
Hopefully this can continue to be maintained as an identical
file.
* python27-sys and python3-sys gain features for explicitly
selecting a python version to link to. for python27-sys,
there's currently only python27; for python3-sys there's
python 3.4 and 3.5.
* explicitly tell travis to use nightlies (seems to have
started trying to use 1.0.0)
=> Python 3 build support

Cargo.toml, python27-sys/Cargo.toml, python3-sys/Cargo.toml, python3-sys/build.rs
Resolves #6.
For python3-sys:
Try to get 'python3' from pkg-config, then fall back to finding any python 3 in the PATH:
`cargo build`
Try to get python3.5 from pkg-config, then fall back to finding a python 3.5 in the PATH:
`cargo build --features python-3-5`
For rust-cpython:
Build against any python 3:
`cargo build --features python3-sys --no-default-features`
Build against a python 3.5
`cargo build --features "python3-sys python-3-5" --no-default-features
=> can build with only a major python 3 version

src/objects/num.rs
The current code of master causes a compile error on a Linux/x86 platform (see a log below).
I read that this is caused by lack of implementation converting to/from i64 for x86, then I create it from current u64 implementation.
Compile error on Linux/x86 (Ubuntu 14.04 x86, rust-nightly)
---------------------------
```
src/objects/num.rs:127:9: 134:10 error: the trait `conversion::ToPyObject<'_>` is not implemented for the type `i64` [E0277]
src/objects/num.rs:127         impl <'p> ToPyObject<'p> for $rust_type {
src/objects/num.rs:128             type ObjectType = <$larger_type as ToPyObject<'p>>::ObjectType;
src/objects/num.rs:129 
src/objects/num.rs:130             #[inline]
src/objects/num.rs:131             fn to_py_object(&self, py: Python<'p>) -> <$larger_type as …
```
=> Fix a compile error on Linux/x86 (implementation of i64 conversion)

build.rs, python27-sys/build.rs, python3-sys/build.rs
can build the ffis for python27-sys, python3-sys; now failing with
src\objects\num.rs:127:9: 134:10 error: the trait `conversion::ToPyObject<'_>` i
s not implemented for the type `i64` [E0277]
src\objects\num.rs:127         impl <'p> ToPyObject<'p> for $rust_type {
src\objects\num.rs:128             type ObjectType = <$larger_type as ToPyObject
<'p>>::ObjectType;
src\objects\num.rs:129
src\objects\num.rs:130             #[inline]
src\objects\num.rs:131             fn to_py_object(&self, py: Python<'p>) -> <$l
arger_type as ToPyObject<'p>>::ObjectType {
src\objects\num.rs:132                 (*self as $larger_type).to_py_object(py)
...
src\objects\num.rs:125:1: 147:3 note: in expansion of int_fits_larger_int!
src\objects\num.rs:171:1: 171:34 note: expansion site
src\objects\num.rs:127:9: …
=> windows support for build scripts

python27-sys/build.rs, python3-sys/build.rs
* pkgconfig is frequently broken or missing, doesn't
contain the explicit path to the interpreter (leading
to bad guesses), and confuses users. Rely on PATH alone.
* Fix bad detection of OSX shared library python
* Fix get_config_from_interpreter reporting python interpreter
path inconsistently with find_interpreter_and_get_config -
fixes OSX python.org python 3, which doesn't have a 'python'
in exec_prefix, just 'python3'
As discussed in #16, also fixes osx issue mentioned in #25, possibly #17
=> Remove pkgconfig approach from -sys builds.

src/objects/list.rs
This PR adds coverage for the list module.
I tried to also put in code to test extraction into vectors, but the following fails to compile:
```rust
#[test]                                                                     
fn test_extract() {                                                         
let gil = Python::acquire_gil();                                        
let py = gil.python();                                                  
let v = vec![2, 3, 5, 7];                                               
let list = v.to_py_object(py).into_object().cast_into::<PyList>().unwrap();
let v2 = list.into_object().extract::<Vec<i32>>().unwrap();             
assert_eq!(v, v2);                                                      
}      
```
The error is:
```
$ cargo test
Compiling …
```
=> Add tests for list.rs. Still missing tests for extract.

src/objects/list.rs, src/objects/mod.rs, src/objects/sequence.rs, src/objects/tuple.rs
This adds support for the Sequence protocol.
Some notes: 
I use `into_object().cast_into::<PySequence>().unwrap()` in the tests because otherwise `to_py_object` would just resolve to the base type (`PyList`, `PyTuple`, etc).
I can't `extract` which I think gets in the way of making interesting assertions on `get_slice` and `set_slice`.
=> Add support for the Sequence protocol

python3-sys/build.rs
The script had two issues: the ```print``` statement and the nonexistent ```MacOS``` module (in Python 3)
I propose this workaround that works fine in my two test systems. The first one uses the system python and prints 'framework' as it should. The second one uses Anaconda and prints 'shared' as expected.
I don't consider myself a *Pythonista* so, if there's a better way to fix this then by all means.
=> get_macos_linkmodel fix

src/err.rs, src/objects/mod.rs
First of all, thank you for this awesome library! This is great for writing native extension modules. This PR adds support for defining custom exception types using `PyErr_NewException` by defining a new macro `py_exception!(modulename, ExceptionName[, BaseExceptionType])`. cc @dgrunwald
=> Add py_exception! macro for defining custom exception types

src/py_class/py_class.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs, tests/test_class.rs
@dgrunwald this adds support for all the inplace methods in `PyNumberMethods` (except for `pow()`, which is actually a ternary function).
=> Add support for in-place numeric operators in py_class!

src/function.rs, src/lib.rs
=> Use uppercase names for static variables to fix warnings

src/py_class/py_class.rs
Add a newline to trigger the proper list formatting
=> Fix __traverse__ list formatting (add missing newline)

README.md
=> Fix typo: Mac OS `dynlib` -> `dylib`

src/argparse.rs, src/lib.rs
I was missing this from #39, and I finally got my head around the code, so here is an implementation of the optional parameters in parameters lists.
I am not sure I understood all the interaction between all the `*Object` traits, so the code might not be optimal. In particular, I don't really get what this line is doing, and if it is the best way to do it:
```rust
$iter.next().unwrap().as_ref().unwrap_or(<$ptype as $crate::ToPyObject>::into_py_object($default, $py).as_object())
```
Tell me what you think!
=> Implement optional values in argparse

README.md
This is a small fix.
Thanks for creating this crate! It's really awesome, and the ability to create Python extension modules is very useful for a project I'm working on.
=> Fix cpython dependency in README.md

python3-sys/Cargo.toml, python3-sys/build.rs
The `.at` method has been replaced by `.get` and now returns a `Match`.
=> Update the regex dependency

python27-sys/src/object.rs, python3-sys/src/object.rs, src/py_class/slots.rs
When creating classes, the `ob_type` field of the class's `PyTypeObject`
is statically initialized to `NULL`, and then becomes dynamically
initialized to `&PyType_Type` when `PyType_Ready()` is called.  This is
too late.  If GC occurs during the initialization of the class before
`PyType_Ready()` is called, then the garbage collector will encounter
the `NULL` `ob_type` and segfault.
The Python docs say this field should be dynamically initialized to
`&PyType_Type` before doing any more class initialization.
=> Initialize ob_type for class type objects early

python27-sys/src/objectabstract.rs
Letting the compiler figure out the pointer size since ARM used u8 for its pointer size instead of i8.
=> Fixing pointer issues for ARM in python27-sys

python27-sys/build.rs, python3-sys/build.rs
The goal of this series is to export the full path to the Python interpreter as a Cargo variable so dependent crates can access the Python that python*-sys is using.
Read the commit messages for more info.
=> Export python interpreter cargo variable

python27-sys/src/lib.rs, python27-sys/src/sysmodule.rs
I needed PySys_SetArgv[Ex] for an embedded Python use case. I went
ahead and declared the other functions.
I skipped PySys_GetFile() because it doesn't exist in Python 3
and we probably shouldn't be encouraging its use. Plus the use of FILE
from Rust is a bit wonky (especially on Windows, since official Python
2.7 distributions are linked against msvcr90 and Rust... won't be -
this would lead to mixing CRTs and badness occuring).
I also skipped _PySys_GetSizeOf(). It is exported. But the leading
underscore means you probably shouldn't use it.
=> Add sysmodule for python27-sys

python27-sys/src/pythonrun.rs
Upstream python removed `_Py_svnversion`, `_Py_hgversion` and
`_Py_hgidentifier` in https://github.com/python/cpython/pull/1327,
replacing them with `_Py_gitversion` and `_Py_gitidentifier`.
These are private symbols which shouldn't be exposed here anyway, so
just remove them.
=> Remove private svn and hg symbols

README.md, extensions/tests/btree.rs, extensions/tests/custom_class.rs, extensions/tests/hello.rs, python27-sys/build.rs, python3-sys/build.rs, src/argparse.rs, src/conversion.rs, src/err.rs, src/lib.rs, src/objectprotocol.rs, src/objects/boolobject.rs, src/objects/module.rs, src/objects/num.rs, src/objects/sequence.rs, src/objects/string.rs, src/objects/tuple.rs, src/py_class/gc.rs, src/py_class/members.rs, src/py_class/py_class.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs
while starting to look at https://github.com/dgrunwald/rust-cpython/issues/159 I noticed an enormous amount of try! macro usages.  The docs for [try](https://doc.rust-lang.org/std/macro.try.html) recommend using `?` instead. I thought I might take a look at this before taking a stab at a bigger pull for the 1.30 macro updates
=> remove usages of try! macro

python3-sys/src/fileutils.rs, python3-sys/src/import.rs, python3-sys/src/lib.rs, python3-sys/src/pythonrun.rs
I've been playing around with Rust applications embedding Python 3 interpreters. There were some APIs missing from python3-sys that I found myself needing. The commits in this series introduce various APIs.
I'm not 100% confident I got some style things correct. But that's what review is for :)
=> Add missing bindings

python27-sys/build.rs, python3-sys/build.rs
Fix extreme case where attempting to build on a machine which only has
"pythonX" or "pythonX.Y" executable.
Previously, if the "python" executable didn't exist on the system,
attempting to call get_config_from_interpreter("python")
resulted in the entire find_interpreter_and_get_config() function to
return Error.
With this change, the abscense of "python" executable will be ignored
and the other executable names will be attempted before giving up.
=> build.rs: Be resilient to the absence of "python" executable

src/argparse.rs, src/buffer.rs, src/err.rs, src/function.rs
Grepped the whole project, fixed with `sed -i` automatically. Fine for now.
In Markdown lists must be either separated from previous paragraph with extra blank line, or be indented with extra spaces at the beginning of each list item.
=> Fix markdown in docs: +extra space before list items

.travis.yml
The old Rust installer has been replaced with rustup.rs.  Use this to
install Rust in Travis.
=> Use rustup.rs to install Rust in Travis builds

Cargo.toml, src/pythonrun.rs
When embedding a Python interpreter in a Rust program, the automatic call
to prepare_freethreaded_python() to initialize the Python interpreter was
causing me problems.
Specifically, I'm doing very dirty things where I've managed to modify the
code that runs as part of Python interpreter startup, before Py_Initialize()
completes. The code that runs is using this crate. That code results
in a call to PyObject::drop(), which calls Python::acquire_gil(),
which calls GILGuard::acquire(), which calls prepare_freethreaded_python(),
which calls Py_InitializeEx(), and leads to reentrant execution because
Py_IsInitialized() returns 0 since the initial call hasn't completed.
I've managed to trigger a Rust panic due to detected reentrancy. I've
also managed to trigger deadlock, apparently due to the …
=> Add "no-auto-initialize" feature to prevent call to prepare_freethreaded_python()

src/argparse.rs, src/err.rs, src/function.rs, src/objects/mod.rs, src/py_class/members.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs, src/py_class/slots.rs
I've updated the macros to work with rust 2018, following the [edition guide](https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html).
=> Make macros work with rust 2018

.travis.yml, tests/check_symbols.py
Based on https://github.com/dgrunwald/rust-cpython/pull/86
For simplicity, we just use the system Python for osx.
=> Add basic support for osx builds in Travis

src/objects/mod.rs, src/objects/set.rs
This exposes the functions that are declared in ffi::setobject.
Since that latter doesn't declare iterators nor update (perhaps for
the same consistency reasons as for dicts ?), we don't have iteration
on Python sets (hence no listing as Vec), nor `update()`.
But this is already enough for Rust extensions to create Python sets
(our primary use-case) and to check membership.
=> Basic implementation for Python sets

python27-sys/src/pythonrun.rs, python3-sys/src/pythonrun.rs
Otherwise we can't set this field when instantiating the struct outside of the module.
=> Make cf_flags in PyCompilerFlags pub

src/function.rs, src/py_class/members.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs
This patch allows `__doc__` of instance methods to be specified using Rust
docstrings, like:
py_class!(... {
///Write something.
///Second line.
def foo(&self, ...) -> ... {
...
}
}
Then `instance.foo.__doc__` would be `"Write something.\nSecond line.\n"` in the
Python world.
Under the hood, Rust translates `/// foo` to `#[doc="foo"]` automatically. So
they can be matched using macros. See https://doc.rust-lang.org/beta/rustdoc/the-doc-attribute.html
=> Use Rust docstring for __doc__ of instance methods

src/objects/capsule.rs, src/objects/mod.rs
Python Capsules are the preferred way to export / import C-level APIs between extension modules (see https://docs.python.org/3/c-api/capsule.html). I believe them to be key for incremental switch to Rust of existing C extensions.
The first commit introduces the `PyCapsule` struct (based on symbols already provided by `python-sys`), the two subsequent ones add macros that take care of the direct function pointer case and caching using `sync::Once` on a `static mut`
=> High level Capsule support

python27-sys/src/lib.rs, python27-sys/src/marshal.rs, python3-sys/src/lib.rs, python3-sys/src/marshal.rs
I had a need for some of these APIs in a project. I went ahead and implemented the full `marshal.h` interface.
=> Implement data marshalling module for python3-sys

src/py_class/members.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs
https://github.com/dgrunwald/rust-cpython/pull/166 continued.
Support for docstrings in class methods and static methods. Slots (special methods) are still not supported and I don't see any way to implement it with Python C API.
=> Docstrings in static and class methods

src/objects/capsule.rs
This follow-up clarifies things for `PyCapsule` use cases where pointers to the C Python objects are
involved.
Some of the capsules from the standard library would probably benefit from this, my first use case would be the [make_dirstate_tuple() capsule of current Mercurial](https://www.mercurial-scm.org/repo/hg/rev/e240bec26626#l4.34)
It would be simpler and a bit more powerful to just add `pub type RawPyObject = ffi::PyObject` to `src/lib.rs`. I don't know if that's acceptable, but I could make a version based on this, also making `cpython::PyObject` API doc a bit less confusing.
=> Capsule: making ffi:PyObject available

.travis.yml, README.md, python3-sys/src/pyerrors.rs, src/argparse.rs, src/function.rs, src/py_class/members.rs, tests/test_class.rs
Make it possible to use Rust keywords for keyword argument and method names.
=> py_class: support Rust raw identifiers for method and keyword names

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, python3-sys/Cargo.toml, python3-sys/src/ceval.rs, python3-sys/src/code.rs, python3-sys/src/compile.rs, python3-sys/src/dictobject.rs, python3-sys/src/fileutils.rs, python3-sys/src/lib.rs, python3-sys/src/moduleobject.rs, python3-sys/src/object.rs, python3-sys/src/objectabstract.rs, python3-sys/src/pyerrors.rs, python3-sys/src/pystate.rs, python3-sys/src/pythonrun.rs
This time around the diff between the Python 3.7.0 and Python 3.8.0 headers was non-trivial; because several parts of the non-limited API were moved around (mostly to the new internal `Include/cpython/*.h` headers).
So it's quite possible that I missed some relevant changes.
It turned out that rust-cpython mostly already works without these changes (enough that all our tests except for `check_symbols.py` pass on Python 3.8 without this PR!).
`PyCodeObject` is obviously broken without this PR, but it's unused in `rust-cpython`.
`PyTypeObject` is a bit more tricky, but in the usual case we're saved because we don't set `_Py_TPFLAGS_HAVE_VECTORCALL`, so an out-of-bounds read should not happen. Only in the rare case when compiling against a Python interpreter using the `COUNT_ALLOCS` mode …
=> Support Python 3.8 in python3-sys.

src/objects/exc.rs
According to https://docs.python.org/3/c-api/exceptions.html these were all defined in PEP 3151 and added in Python 3.3.
=> Define Python 3 exceptions from PEP 3151

python3-sys/src/import.rs
The struct and function are documented at
https://docs.python.org/3/c-api/import.html#c._inittab
and defined in source code (in CPython master) at
https://github.com/python/cpython/blob/51edf8aaa2e17626f9690ed29d25945fc03016b9/Include/cpython/import.h#L30.
It is unclear whether PyImport_Inittab is part of the official
API, as it isn't clearly documented. But the static has been
shipping for years and is still in CPython master. I need to
use this variable in PyOxidizer in order to modify the set
of extensions at run-time. Putting it behind Py_LIMITED_API
should be safe.
=> Define inittab entities

src/function.rs
The first form macro is called by `py_fn!`, and calls `py_method_def!`
again with a default value for the docstring.
But it didn't bear the `local_inner_macros` modifier so that fails.
Adding that modifier forces us to rewrap `concat!` as done before
with `stringify!`.
Reference: https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-using-local_inner_macros
=> Edition 2018: made `py_method_def!` usable from external crates.

Cargo.toml, build.rs, python3-sys/Cargo.toml, python3-sys/build.rs
As part of developing PyOxidizer, I needed to force python3-sys to
statically link against a Python library on Windows in a downstream
crate of python3-sys. This requires the unstable `static-nobundle`
link type so Cargo leaves symbols as unresolved when python3-sys
is built. (Currently, the `static` linkage type verifies referenced
symbols are present at crate build time.) See
https://github.com/rust-lang/rust/issues/37403 for more. Look for
comments by me (@indygreg) to describe the issue in more detail.
This commit teaches python3-sys a pair of new build features which
enable more explicit control over the linker directives emitted by
its build script. If no directive is specified, `link-mode-default`
is used and the existing logic for linker directive emission is
used. If …
=> Support link mode control

src/argparse.rs, src/err.rs, src/objects/exc.rs, src/objects/iterator.rs, src/objects/mod.rs, src/objects/string.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs, src/python.rs
When TypeErrors are generated from PythonObjectDowncastErrors, include
the type that the downcast was targetted at, and the type of the object
that was being targetted.
This results in errors like:
TypeError: Expected type that converts to PyString but received int
=> improve PythonObjectDowncastError TypeErrors

src/sharedref.rs
Anyone copy-pasting the code and trying to use the new `@shared` interface for the first time will get an error about leaking a private type.
=> Add missing `pub` classifier

python3-sys/src/import.rs, python3-sys/src/modsupport.rs
I need some of these APIs to support in-memory extension module
importing in PyOxidizer. While I was adding the ones I needed, I
figured I would include some other missing symbols from
import.h as well.
=> Add more import APIs

src/argparse.rs, src/err.rs, src/objects/dict.rs, src/objects/string.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs, src/py_class/slots.rs, tests/test_class.rs, tests/test_function.rs
This allows slot implementations with a single parameter (in particular,
`__compare__`, `__getitem__`, `__delitem__`, and in-place operators like `__iadd__`),
as well as `__richcmp__` to work with reference types (types that implement
RefFromPyObject) as well as full types (types that implement FromPyObject).
Additionally, optional references are included.  This is an improvement over
normal methods, so this is extended to normal methods, too.
The syntax is the same as for methods, e.g.
def __contains__(&self, key: &KeyType) -> PyResult<bool>
will generate a method where the key will be borrowed from the PyObject,
rather than copied.
Similarly for optional references:
def __contains__(&self, key: Option<&KeyType>) -> PyResult<bool>
will be the same, except that the key will be `None` if …
=> Implement reference extraction for slot functions and optional reference extraction

src/argparse.rs, src/err.rs, src/function.rs, src/lib.rs, src/objects/dict.rs, src/objects/string.rs, src/py_class/members.rs, src/py_class/py_class.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs, src/py_class/slots.rs, tests/test_class.rs, tests/test_function.rs
Add support for defining Python properties (attributes with getters and optional setters) in Rust.
Properties are defined inside `py_class!` with:
@property def property_name(&self) -> PyResult<PropertyType> { ... }
where `property_name` is the name in Python, and `PropertyType` is any type that impls `ToPyObject`.
Property setters can optionally be defined as:
@property_name.setter def set_property_name(
&self,
value: Option<PropertyType>
) -> PyResult<()> { ... }
If the value is `None` then the caller is deleting the property (`del obj.property_name`).
If the value is `Some(x)` then the caller is setting the property to `x`.
For setters, the `PropertyType` can be any type that impls `FromPyObject`, or a reference or optional reference to any type that impls `RefFromPyObject`.
In the …
=> Implement property support

python3-sys/src/initconfig.rs, python3-sys/src/lib.rs, python3-sys/src/pylifecycle.rs
Python 3.8 implements several new APIs around interpreter configuration
and initialization as defined by PEP-587.
I will want to use many of these APIs in PyOxidizer.
This commit defines the new APIs.
The new APIs are split in CPython source between Include/initconfig.h
and Include/cpython/pylifecycle.h. All of the APIs are outside the
Py_LIMITED_API scope.
We didn't have a pylifecycle.rs for the existing Include/pylifecycle.h.
Assuming we don't want to have different Rust modules distinguish between
the Include/<foo>.h and Include/cpython/<foo>.h variants (which appear
to have been introduced in CPython 3.8 - to help split Py_LIMITED_API I
think), I went ahead and created pylifecycle.rs. Ideally the Rust
modules would reflect the current state of the symbols in the latest
CPython …
=> Implement PEP-587 initialization APIs

CHANGELOG.md, Cargo.toml, README.md, extensions/hello/Cargo.toml, python27-sys/Cargo.toml, python3-sys/Cargo.toml, src/py_class/py_class.rs, tests/test_class.rs
Tried to make some things more explicit in the documentation of properties, and then proceed to the 0.5.0 release.
I'll merge this myself, so that I can upload to `crates.io` and put a tag right away.
=> Release 0.5.0 and some doc clarifications

python27-sys/src/lib.rs, python3-sys/src/import.rs, python3-sys/src/lib.rs
Run the code through `rustfmt` again - the latest additions to python3-sys were not formatted.
Suppress the `unused_parens` warnings in the sys crates.  These trigger on code like:
```
pub const PyBUF_STRIDES: c_int = (0x0010 | PyBUF_ND);
```
We should keep these as they match the C header.
=> Format code and suppress unused_parens warnings

.travis.yml
Since there's a good difference between our minimal supported Rust version
and the current stable, I feel it's worthwile to add a case with Rust
stable.
=> Travis CI: also testing on Rust stable

python3-sys/src/initconfig.rs
The structs added in #211 did not have public fields. The
fields need to be public in order to allow modifying them.
Furthermore, instantiating new instances of these structs would
be cumbersome (even with public fields) because there are so
many fields. So, we implement Default to construct new instances
that are zero initialized.
=> Make fields of initialization config public and implement Default

src/py_class/members.rs, src/py_class/slots.rs
Some macro definitions are missing `$crate::` in their calls to other macros.  Add them.
Fixes #234
=> Fix macros without $crate:: access

Cargo.toml, src/objects/string.rs
The current logic that converts a PyString to either bytes or unicode
on Python 2 makes the `PyString` or `String` type less useful in
applications that pay closer attention to the actual type of bytes vs
string.
Add a feature, once set, PyString and String will be consistently
converted to the `str` type on both Python 2 and Python 3, regardless
of their actual content. This meets expections of type-sensitive
applications that still use Python 2.
The feature is disabled by default conservatively for backwards
compatibility.
=> Add a way to disable converting PyString to unicode on Python 2

Cargo.toml, Makefile, src/lib.rs, src/serde/de.rs, src/serde/error.rs, src/serde/mod.rs, src/serde/ser.rs, src/serde/tests.rs
Converts between serde types and PyObject. This can make FromPyObject/
ToPyObject implementations easier.
=> Initial serde support

Cargo.toml, Makefile, src/function.rs, src/serde/de.rs, src/serde/tests.rs, tests/test_thread_exit.rs
The AbortOnDrop is used in this pattern:
let guard = AbortOnDrop(...);
call_into_python(...);
mem::forget(guard);
There is a special case that call_into_python does not return
(ex. the thread gets dropped). If that happens with pthread backend,
the `mem::forget` does not run, but `guard::drop` still runs, causing
the program to abort.
Remove AbortOnDrop to make that multi-thread case work.
=> Avoid abort() if the Python function never returns (thread exit)

.travis.yml, README.md, python3-sys/Cargo.toml, python3-sys/src/ceval.rs, python3-sys/src/compile.rs, python3-sys/src/frameobject.rs, python3-sys/src/import.rs, python3-sys/src/initconfig.rs, python3-sys/src/lib.rs, python3-sys/src/methodobject.rs, python3-sys/src/modsupport.rs, python3-sys/src/object.rs, python3-sys/src/objectabstract.rs, python3-sys/src/objimpl.rs, python3-sys/src/pystate.rs, python3-sys/src/pythonrun.rs, python3-sys/src/tupleobject.rs, python3-sys/src/unicodeobject.rs
As usual with new Python releases, I diffed the 3.8.0 Python headers against the 3.9.0 Python headers and manually made these adjustments to python3-sys.
While rust-cpython could be compiled against Python 3.9 without these changes, there were some breaking changes to the headers:
* some macros like `PyObject_IS_GC` or `PyObject_GET_WEAKREFS_LISTPTR` were replaced with functions
* some functions were removed from the API
* `PyConfig` had breaking changes to the struct layout
=> Add Python 3.9 support

tests/test_thread_exit.rs
This test no longer works, so disable it.
I'm not sure what to do about the wider question of correctly handling `pthread_exit`.
=> Disable test_thread_exit on Rust >= 1.48

Cargo.toml
This commit also adds excludes for one more file (Makefile), as that file is not useful in published crates.
=> Bump from paste 0.1 to 1

.travis.yml, README.md
The `thread_local` dependency now requires a minimum Rust version of
1.36.  Increase our MSRV to 1.41.1, which is the version in Debian
stable.
=> Increase MSRV to 1.41.1

python3-sys/src/unicodeobject.rs, src/objects/string.rs
This fixes #246: panic in `PyString::to_string` and `PyString::to_string_lossy` when a Python3 unicode string contains unpaired surrogates.
As an optimization, `PyString::to_string` keeps using `PyUnicode_AsUTF8AndSize` which allows Python to cache the UTF-8 representation.
=> `PyString::data()`: return the internal representation of the Python unicode object

README.md, python27-sys/src/lib.rs, python3-sys/src/initconfig.rs, python3-sys/src/lib.rs, python3-sys/src/methodobject.rs, python3-sys/src/modsupport.rs, python3-sys/src/object.rs, python3-sys/src/pystate.rs, src/py_class/py_class.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs, tests/test_class.rs
Teach the `py_class` macros about allowing arbitrary visibility keywords (e.g., `pub(crate)`) on class definitions and the method definitions within that class definition. This PR also makes the `create_instance` method have the same visibility as the class.
[The `vis` capture type for visibility in macro_rules has been available since Rust v1.30.0.](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1300-2018-10-25)  Given that this crate requires v1.32 or higher, this PR does not break the crate's compatibility guarantee.
Note: The ultimate motivation for this PR is to allow me to split a very complicated use of this crate into multiple modules without having to make many types `pub`.
=> allow all visibility keywords on classes and functions

extensions/hello/src/hello.rs, extensions/tests/custom_class.rs, extensions/tests/hello.rs, src/argparse.rs, src/conversion.rs, src/objects/mod.rs, src/objects/none.rs, src/objects/object.rs, src/py_class/slots.rs, src/serde/de.rs, tests/test_class.rs, tests/test_function.rs
Add a new zero-sized struct `PyNone`, that represents Python's `None`.  This is
similar to `NoArgs` for the empty tuple, and is useful for defining functions
or methods that return None in Python.
=> Add PyNone to represent Python None

build.rs, python27-sys/build.rs, python3-sys/build.rs
When changing environment variables relevant to the build, Cargo should re-run our build scripts.
Tell cargo [that we have accessed env vars](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script).
=> Build scripts should invalidate when relevant env vars change

Makefile, tests/check_symbols.py
`-Z ast-json` ist no longer available in Rust nightly, see also https://github.com/dgrunwald/rust-cpython/pull/279#issuecomment-1159658662. Suggestion: Let `nm` report undefined symbols. This should also work for Rust stable.
=> Replace -Z ast-json in the check for undefined symbols

src/argparse.rs, src/function.rs, src/py_class/py_class.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs
Sometimes the `py` parameter of `py_class!` is only used in some class methods and not others. The current implementation of cpython's macros makes Rust produce a warning in this situation, which does not seem good.
Repro:
```rust
use cpython::{py_class, PyResult};
py_class!(class Struct |py| {
data number: i32;
def __new__(_cls, n: i32) -> PyResult<Struct> {
Struct::create_instance(py, n)
}
def get_number(&self) -> PyResult<i32> {
Ok(*self.number(py))
}
def get_random(&self) -> PyResult<i32> {
Ok(4)
}
});
```
```console
warning: unused variable: `py`
--> src/lib.rs:3:25
|
3 | py_class!(class Struct |py| {
|                         ^^ help: if this is intentional, prefix it with an underscore: `_py`
|
= note: `#[warn(unused_variables)]` on by default
```
Following the compiler's suggested …
=> Eliminate warnings on an unused `py`

src/err.rs, src/lib.rs, src/objects/exc.rs, src/objects/mod.rs, src/py_class/py_class_impl.py, src/py_class/py_class_impl2.rs, src/py_class/py_class_impl3.rs
Without this, importing any other crate's `Result` type alias in a module that uses cpython's macros causes compilation to fail in a variety of interesting ways.
Repro:
```rust
use cpython::{py_class, PyResult};
use std::io::Result;
py_class!(class Struct |py| {
def __new__(_cls) -> PyResult<Struct> {
Struct::create_instance(py)
}
});
```
The resulting diagnostic:
```console
error[E0107]: this type alias takes 1 generic argument but 2 generic arguments were supplied
--> src/main.rs:4:1
|
4  | / py_class!(class Struct |py| {
5  | |     def __new__(_cls) -> PyResult<Struct> {
6  | |         Struct::create_instance(py)
7  | |     }
8  | | });
| |  ^
| |  |
| |__expected 1 generic argument
|    help: remove this generic argument
|
note: type alias defined here, with 1 generic parameter: `T` …
```
=> Consistently refer to the right `Result` in macro expansion

.github/workflows/test.yml
https://github.com/dtolnay/rust-toolchain seems to be active, maybe this can also fix the build problems on the py3.11 branch.
=> Update actions, try other action for providing the rust toolchain

Cargo.toml, python3-sys/Cargo.toml, python3-sys/src/code.rs, python3-sys/src/frameobject.rs, python3-sys/src/object.rs, python3-sys/src/pyerrors.rs, python3-sys/src/pystate.rs
This is obviously experimental but it works okay.
All the tests pass and the example prints the following:
> $ cargo run --example hello --features python-3-11
> Hello nicholas, I'm Python 3.11.0b1 (v3.11.0b1:8d32a5c8c4, May  6 2022, 22:45:29) [Clang 13.0.0 (clang-1300.0.29.30)]
I figure it's best to be proactive with these change, so that way we are ready as soon as 3.11 proper is released (October I think).
MAin difference in 3.11 that frame object is now private (and lazy loaded).
This results in a performance improvement but makes it harder for debuggers.
Also the internal ordering of code objects has completely changed as well.
=> Initial support for Python 3.11 beta

.github/workflows/test.yml, README.md, python3-sys/src/code.rs, python3-sys/src/compile.rs, python3-sys/src/initconfig.rs, python3-sys/src/modsupport.rs, python3-sys/src/object.rs, python3-sys/src/objimpl.rs, python3-sys/src/unicodeobject.rs, tests/check_symbols.py
I looked at all Py_3_12 changes in pyo3-ffi/src/cpython and ported them back. Functions, structs, and fields in the code object not already defined in python3-sys are ignored. For PyUnicode_READY, I kept a dummy version so the cpython crate does not need change.
Fixes #294 and https://github.com/facebook/sapling/issues/895
=> python3-sys: port Py_3_12 changes from pyo3-ffi
